server:
  port: 8080

spring.jackson.date-format: com.flmaster.calculator.invoker.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

settings:
  admin:
    login: admin
    password: $2a$08$G3bpuMAXGrqRqKwOiOpxj.Uc4h2xpCr/31/lvP4eKuUg0KKGzH456
